version: "3.9"  # optional since v1.27.0
services:
  postgres:
    image: postgres
    container_name: mypostgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=spacedb
  pgadmin:
    image: dpage/pgadmin4
    container_name: mypgadmin
    ports:
      - "7777:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin